# Generated by Django 4.2.4 on 2024-05-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='color',
            field=models.CharField(default='white', max_length=200),
        ),
    ]
