# Generated by Django 4.2.4 on 2024-05-01 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_choice_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Rect',
        ),
    ]
