# Generated by Django 4.2.4 on 2024-05-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_rename_choice_rect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
