# Generated by Django 4.2.4 on 2024-05-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_tag_image_description_image_publication_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='pub_date',
        ),
    ]
