# Generated by Django 4.2.4 on 2024-05-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_remove_image_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increasing', models.BooleanField()),
            ],
        ),
    ]
