# Generated by Django 4.2.4 on 2024-05-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
